//! Simple internal request types for DGNA (Dynamic Group Number Assignment).
//!
//! This is **not** an ETSI SAP. It's an internal message used by the HTTP UI
//! to ask the MM entity to send a D-ATTACH/DETACH GROUP IDENTITY PDU to one or
//! more target ISSIs.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DgnaOp {
    Attach,
    Detach,
}

/// DGNA request generated by UI.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DgnaSetReq {
    /// Job id (created by the UI) used to track status.
    pub job_id: u64,
    /// Attach or detach.
    pub op: DgnaOp,
    /// Target subscribers (ISSI list).
    pub targets: Vec<u32>,
    /// Target group to attach/detach.
    pub gssi: u32,
    /// If true, detach all groups first ("transfer" semantics).
    pub detach_all_first: bool,
    /// Requested attachment lifetime (3 bits in GroupIdentityAttachment).
    pub lifetime: u8,
    /// Class of usage (3 bits in GroupIdentityAttachment).
    pub class_of_usage: u8,
    /// Ask MS to reply with U-ATTACH/DETACH GROUP IDENTITY ACK.
    pub ack_req: bool,
}
